// This file is auto-generated by `ember build`.
// You should not modify it.

var App = window.App = require('./config/app');
require('./templates');


App.EditPerformerController = require('./controllers/edit_performer_controller');
App.NewPerformerController = require('./controllers/new_performer_controller');
App.PerformerController = require('./controllers/performer_controller');
App.Performer = require('./models/performer');
App.NewPerformerRoute = require('./routes/new_performer_route');
App.PerformersRoute = require('./routes/performers_route');

require('./config/routes');

module.exports = App;

